class Planetutils < Formula
  desc "Maintain, cut, convert and download OpenStreetMap planets and extracts"
  homepage "https://github.com/interline-io/planetutils"
  url "https://github.com/interline-io/planetutils/releases/download/v1.0.0/interline_planetutils-1.0.0-py3-none-any.whl", using: :nounzip
  sha256 "d6acb78471c0f7d6dec2685d0e8549b94c1b8df21ea1080cd7d7cfba4f15615a"
  license "MIT"

  # osm_planet_extract (osmium is its default toolchain) and
  # osm_extract_convert shell out to osmium-tool; everything else runs from
  # Python wheels. Rasterio bundles GDAL in its wheel. For
  # --toolchain=osmosis or osmctools, install those formulae separately.
  depends_on :macos
  depends_on "osmium-tool"
  depends_on "python@3.13"

  # Python dependencies are prebuilt wheels pinned to the release's uv.lock --
  # the set its CI tested. To update for a new release:
  #   uv run scripts/update-planetutils.py <version>

  # BEGIN GENERATED RESOURCES
  # Generated by scripts/update-planetutils.py from the release's uv.lock.
  # Do not edit by hand.

  on_arm do
    resource "numpy" do
      url "https://files.pythonhosted.org/packages/ab/2a/98282aa5b8f58b1157d440bb6282eed47e3632a5de53a714fbab17e659fe/numpy-2.5.3-cp313-cp313-macosx_14_0_arm64.whl", using: :nounzip
      sha256 "f9a2353b37a1a9e78fd82b27ad7e2a32a2d036604d18f02b05e3136c62ca3b09"
    end

    resource "osmium" do
      url "https://files.pythonhosted.org/packages/a5/81/3c4bd92415292d3b628dd04f117da1f179ffa3c8ad1c2028f201c5c721d8/osmium-4.3.1-cp313-cp313-macosx_11_0_arm64.whl", using: :nounzip
      sha256 "0f87db2d4faad40968248561df188054826ef536359598c111b8c0fe021852c1"
    end

    resource "rasterio" do
      url "https://files.pythonhosted.org/packages/c9/f0/d3c613d845b35a3800b812f0fe0351675f6310972bbd6349f844499ebd6a/rasterio-1.5.1-cp313-cp313-macosx_14_0_arm64.whl", using: :nounzip
      sha256 "937944c445d4ea4d6969e9dbfcf305143c05fc4df2f8fadfa360cb2d0f65d7b0"
    end
  end

  on_intel do
    resource "numpy" do
      url "https://files.pythonhosted.org/packages/a1/f9/b6533d777be9d6ffd29dc1be0867e563e6e8cc9a220ff1b716adc317f060/numpy-2.5.3-cp313-cp313-macosx_14_0_x86_64.whl", using: :nounzip
      sha256 "ccbc4665079665c3cf3bab4db9f6b095370cd6437d66be549b6c2a1fd19e1958"
    end

    resource "osmium" do
      url "https://files.pythonhosted.org/packages/56/c2/b9b9a9137dc7ff8b99bda19e1f566ba05ad9999ceaed3c3e5a09bacd29ba/osmium-4.3.1-cp313-cp313-macosx_11_0_x86_64.whl", using: :nounzip
      sha256 "a6d55da027bc2ce884c4937fd0a7efbe2c04b706fef8e438fb2293e24c8c7f60"
    end

    resource "rasterio" do
      url "https://files.pythonhosted.org/packages/e9/ca/54c1976340df39ea6bd77ff4b41eec932ff260b635a8512ceae0945595c4/rasterio-1.5.1-cp313-cp313-macosx_15_0_x86_64.whl", using: :nounzip
      sha256 "e863b614cadad435a4394792b6cdc84324b15197629ad5a20c8d56cbc4eeff92"
    end
  end

  resource "affine" do
    url "https://files.pythonhosted.org/packages/3d/87/e62f55c956b583380e7d2a71705dfd431ee32dd1689d50491ba0c610fc11/affine-3.0.1-py3-none-any.whl", using: :nounzip
    sha256 "cda3b303325e7bf2bf34817e68753a0d1c4cacbdd451fe67c4878dc2ecbaa540"
  end

  resource "attrs" do
    url "https://files.pythonhosted.org/packages/64/b4/17d4b0b2a2dc85a6df63d1157e028ed19f90d4cd97c36717afef2bc2f395/attrs-26.1.0-py3-none-any.whl", using: :nounzip
    sha256 "c647aa4a12dfbad9333ca4e71fe62ddc36f4e63b2d260a37a8b83d2f043ac309"
  end

  resource "certifi" do
    url "https://files.pythonhosted.org/packages/0b/a7/71ac2cff56fec219ed242bb11b8efb69fcc4bec75db06fb7bfe35de520e6/certifi-2026.7.22-py3-none-any.whl", using: :nounzip
    sha256 "62f22742b58a1a33014a2b6b706588a8d7e2a88ae7bd1a6ebe8c992928483775"
  end

  resource "charset-normalizer" do
    url "https://files.pythonhosted.org/packages/a4/a0/562247944386f7d4ef94467e84876600cc1e0f1b93239aaa9213d2bc3cbd/charset_normalizer-3.5.1-cp313-cp313-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "e90251c0c7bdd54a100a0dce3c07b7e637278c93af29dbf78ebb89a58c4bac7d"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/58/50/6c0d534c5f134586a8e1ba4e330569e32f057e33372ae556463212fb4cd3/click-8.5.0-py3-none-any.whl", using: :nounzip
    sha256 "255bc9599cf7748b4b1a446ccc735421bd08a2ae529a8b88597d3de5664ee360"
  end

  resource "idna" do
    url "https://files.pythonhosted.org/packages/58/a2/bb081bab032533a855d44de1d56f8e8426114ff1ba5d1f07a438a0a654f8/idna-3.20-py3-none-any.whl", using: :nounzip
    sha256 "ab7ae7122974553370f0bdb919e1a960b2cd1bc1ef0276416d896db81c14582c"
  end

  resource "pyparsing" do
    url "https://files.pythonhosted.org/packages/10/bd/c038d7cc38edc1aa5bf91ab8068b63d4308c66c4c8bb3cbba7dfbc049f9c/pyparsing-3.3.2-py3-none-any.whl", using: :nounzip
    sha256 "850ba148bd908d7e2411587e247a1e4f0327839c40e2e5e6d05a007ecc69911d"
  end

  resource "requests" do
    url "https://files.pythonhosted.org/packages/a0/f4/c67b0b3f1b9245e8d266f0f112c500d50e5b4e83cb6f3b71b6528104182a/requests-2.34.2-py3-none-any.whl", using: :nounzip
    sha256 "2a0d60c172f83ac6ab31e4554906c0f3b3588d37b5cb939b1c061f4907e278e0"
  end

  resource "urllib3" do
    url "https://files.pythonhosted.org/packages/92/9d/c4e665119135114480843e7ab388fa94d8480650450e6f8e26b70d323a4c/urllib3-2.8.0-py3-none-any.whl", using: :nounzip
    sha256 "0cf3cae568d36aa9576b28dfb35f11328f1cb974ca7647d9475ebb86c75ac6e3"
  end
  # END GENERATED RESOURCES

  def install
    python = formula_opt_bin("python@3.13")/"python3.13"
    system python, "-m", "venv", "--without-pip", libexec
    wheels = buildpath/"wheels"
    resources.each { |r| r.stage(wheels) }
    # Only the checksummed wheels staged here: no index, no dependency
    # resolution, nothing fetched at install time.
    system python, "-m", "pip", "--python=#{libexec}/bin/python", "install",
           "--no-index", "--no-deps", "--only-binary=:all:", "--no-compile",
           *wheels.glob("*.whl"), *buildpath.glob("*.whl")
    bin.install_symlink libexec.glob("bin/{osm,elevation,valhalla}_*")
  end

  test do
    %w[
      osm_planet_update osm_planet_extract osm_planet_get_timestamp
      osm_extract_download osm_extract_convert
      elevation_tile_download elevation_tile_merge
      valhalla_tilepack_download valhalla_tilepack_list
    ].each do |cmd|
      assert_match "usage:", shell_output("#{bin}/#{cmd} --help")
    end

    (testpath/"tiny.osm").write <<~XML
      <?xml version="1.0" encoding="UTF-8"?>
      <osm version="0.6" generator="test">
        <node id="1" version="1" timestamp="2026-01-01T00:00:00Z" lat="0.5" lon="0.5">
          <tag k="amenity" v="cafe"/>
        </node>
        <node id="2" version="1" timestamp="2026-01-01T00:00:00Z" lat="5" lon="5">
          <tag k="amenity" v="bar"/>
        </node>
      </osm>
    XML
    system bin/"osm_planet_extract", "--bbox=0,0,1,1", "--name=box", "tiny.osm"
    system bin/"osm_extract_convert", "box.osm.pbf"
    geojson = (testpath/"box.geojson").read
    assert_match "cafe", geojson
    refute_match "bar", geojson
  end
end
