#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["packaging>=24"]
# ///
"""Update Formula/planetutils.rb for a PlanetUtils release.

    uv run scripts/update-planetutils.py 1.0.0

Points the formula at the release's wheel, then regenerates the Python
dependency resources from the release's uv.lock -- the exact set its CI
tested. `uv export --format pylock.toml` lists every wheel with its sha256;
this keeps one wheel per package for the formula's Python on each macOS
architecture Homebrew supports, and writes them as resources between the
BEGIN/END GENERATED RESOURCES markers.
"""
import hashlib
import subprocess
import sys
import tempfile
import tomllib
import urllib.request
from pathlib import Path

from packaging.markers import Marker
from packaging.tags import compatible_tags, cpython_tags, mac_platforms
from packaging.utils import parse_wheel_filename

REPO = 'interline-io/planetutils'
FORMULA = Path(__file__).resolve().parent.parent / 'Formula' / 'planetutils.rb'
PYTHON = (3, 13)  # keep in step with depends_on "python@3.13"
# Homebrew's oldest supported macOS (HOMEBREW_MACOS_OLDEST_SUPPORTED). A wheel
# built for this version or older installs on every Mac Homebrew supports.
MACOS = (15, 0)
ARCHES = {'arm': 'arm64', 'intel': 'x86_64'}
BEGIN = '  # BEGIN GENERATED RESOURCES'
END = '  # END GENERATED RESOURCES'


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def lock_packages(version):
    """The release's dependencies, as pylock.toml packages, from its uv.lock."""
    with tempfile.TemporaryDirectory() as d:
        for name in ('pyproject.toml', 'uv.lock'):
            url = 'https://raw.githubusercontent.com/%s/v%s/%s' % (REPO, version, name)
            (Path(d) / name).write_bytes(fetch(url))
        out = subprocess.run(
            ['uv', 'export', '--frozen', '--no-dev', '--no-emit-project',
             '--format', 'pylock.toml', '--directory', d],
            check=True, capture_output=True, text=True).stdout
    return tomllib.loads(out)['packages']


def environment(arch):
    return {
        'python_version': '%d.%d' % PYTHON,
        'python_full_version': '%d.%d.0' % PYTHON,
        'implementation_name': 'cpython',
        'platform_python_implementation': 'CPython',
        'sys_platform': 'darwin',
        'platform_system': 'Darwin',
        'os_name': 'posix',
        'platform_machine': arch,
    }


def supported_tags(arch):
    """Tags installable on MACOS, most preferred first."""
    platforms = list(mac_platforms(MACOS, arch))
    return list(cpython_tags(PYTHON, platforms=platforms)) + list(
        compatible_tags(PYTHON, 'cp%d%d' % PYTHON, platforms=platforms))


def pick_wheel(package, tags):
    """The most preferred wheel that installs on `tags`, or None."""
    rank = {tag: i for i, tag in enumerate(tags)}
    best = None
    for wheel in package.get('wheels', []):
        filename = wheel['url'].rsplit('/', 1)[-1]
        _, _, _, wheel_tags = parse_wheel_filename(filename)
        score = min((rank[t] for t in wheel_tags if t in rank), default=None)
        if score is not None and (best is None or score < best[0]):
            best = (score, wheel)
    return best and best[1]


def resolve(packages):
    """{arch_key: {name: wheel}} for every package that applies there."""
    chosen = {}
    for key, arch in ARCHES.items():
        env, tags = environment(arch), supported_tags(arch)
        chosen[key] = {}
        for package in packages:
            marker = package.get('marker')
            if marker and not Marker(marker).evaluate(env):
                continue
            wheel = pick_wheel(package, tags)
            if wheel is None:
                sys.exit('no wheel of %s %s installs on macOS %d / %s / Python %d.%d'
                         % (package['name'], package['version'], MACOS[0], arch, *PYTHON))
            chosen[key][package['name']] = wheel
    return chosen


def resource(name, wheel, indent):
    pad = ' ' * indent
    return [
        '%sresource "%s" do' % (pad, name),
        '%s  url "%s", using: :nounzip' % (pad, wheel['url']),
        '%s  sha256 "%s"' % (pad, wheel['hashes']['sha256']),
        '%send' % pad,
    ]


def resource_block(chosen):
    names = sorted(set().union(*(c.keys() for c in chosen.values())))
    shared = [n for n in names if all(c.get(n) == chosen['arm'].get(n) for c in chosen.values())]
    lines = [BEGIN,
             '  # Generated by scripts/update-planetutils.py from the release\'s uv.lock.',
             '  # Do not edit by hand.']
    # brew style wants on_arm/on_intel ahead of top-level resources.
    for key in ARCHES:
        specific = [n for n in names if n not in shared and n in chosen[key]]
        if specific:
            lines += ['', '  on_%s do' % key]
            for i, name in enumerate(specific):
                lines += ([''] if i else []) + resource(name, chosen[key][name], 4)
            lines += ['  end']
    for name in shared:
        lines += [''] + resource(name, chosen['arm'][name], 2)
    return lines + [END]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    version = sys.argv[1].lstrip('v')
    wheel_url = 'https://github.com/%s/releases/download/v%s/interline_planetutils-%s-py3-none-any.whl' % (
        REPO, version, version)
    wheel_sha = hashlib.sha256(fetch(wheel_url)).hexdigest()
    chosen = resolve(lock_packages(version))

    lines = FORMULA.read_text().splitlines()
    if BEGIN not in lines or END not in lines:
        sys.exit('%s needs the %r and %r markers' % (FORMULA, BEGIN.strip(), END.strip()))
    # The formula's own url and sha256 are the first two-space-indented ones;
    # resources are indented further.
    i = next(i for i, line in enumerate(lines) if line.startswith('  url "'))
    if not lines[i + 1].startswith('  sha256 "'):
        sys.exit('expected sha256 on the line after the formula url')
    lines[i] = '  url "%s", using: :nounzip' % wheel_url
    lines[i + 1] = '  sha256 "%s"' % wheel_sha
    begin, end = lines.index(BEGIN), lines.index(END)
    lines[begin:end + 1] = resource_block(chosen)
    FORMULA.write_text('\n'.join(lines) + '\n')
    counts = {k: len(v) for k, v in chosen.items()}
    print('planetutils %s: %s' % (version, ', '.join('%d resources on %s' % (n, k) for k, n in counts.items())))


if __name__ == '__main__':
    main()
